package com.seljabali.widgets.landing

import com.seljabali.widgets.R

enum class Widgets (val title:String, val drawable: Int) {
    AnalogClock("Analog Clock", R.drawable.analog_clock),
    AutoCompleteTextView("AutoComplete TextView", R.drawable.autocomplete_textview),
    Button("Button", R.color.transparent),
    CalendarView("Calendar", R.color.transparent),
    CheckBox("CheckBox", R.drawable.checkbox),
    CheckedTextView("Checked Text View", R.color.transparent),
    Chronometer("Chronometer", R.drawable.chronometer),
    CompoundButton("Compound Button", R.color.transparent),
    DatePicker("Date Picker", R.drawable.date_picker),
    EdgeEffect("Edge Effect", R.color.transparent),
    EditText("EditText", R.color.transparent),
    GridLayout("GridLayout", R.color.transparent),
    GridView("Grid View", R.color.transparent),
    ImageButton("Image Button", R.color.transparent),
    ImageSwitcher("Image Switcher", R.color.transparent),
    ImageView("Image View", R.color.transparent),
    Magnifier("Magnifier", R.color.transparent),
    MediaController("Media Controller", R.color.transparent),
    MultiAutoCompleteTextView("Multi Auto Complete Text View", R.color.transparent),
    NumberPicker("Number Picker", R.color.transparent),
    ProgressBar("Progress Bar", R.drawable.progress_bar),
    RadioButton("Radio Button", R.drawable.radio_buttons),
    RatingBar("Rating Bar", R.color.transparent),
    SeekBar("Seek Bar", R.drawable.seek_bar),
    StatusBar("Status Bar", R.drawable.status_bar),
    TextClock("Text Clock", R.drawable.text_clock),
    TimePicker("Time Picker", R.drawable.time_picker),
    Toast("Toast", R.drawable.toast),
    ToolBar("Tool Bar", R.drawable.tool_bar),
}