package com.seljabali.widgets.landing

import com.seljabali.widgets.R

enum class Widgets (val title:String, val drawable: Int) {
    AnalogClock("Analog Clock", R.drawable.analog_clock),
    AutoCompleteTextView("AutoComplete Text View", R.drawable.autocomplete_textview),
    Badge("Badge", R.color.transparent),
    BiometricPrompt("Biometric Prompt", R.mipmap.fingerprint),
    BottomAppBar("Bottom App Bar", R.color.transparent),
    BottomNavigation("Bottom Navigation", R.color.transparent),
    BottomSheet("Bottom Sheet", R.color.transparent),
    Button("Button", R.color.transparent),
    CalendarView("Calendar", R.color.transparent),
    CardView("Card View", R.color.transparent),
    CheckBox("Checkbox", R.drawable.checkbox),
    CheckedTextView("Checked Text View", R.color.transparent),
    Chips("Chips", R.color.transparent),
    Chronometer("Chronometer", R.drawable.chronometer),
    CompoundButton("Compound Button", R.color.transparent),
    DatePicker("Date Picker", R.drawable.date_picker),
    Dialog("Dialog", R.color.transparent),
    DialogFragment("Dialog Fragment", R.color.transparent),
    DrawerLayout("Drawer Layout", R.color.transparent),
    EdgeEffect("Edge Effect", R.color.transparent),
    EditText("EditText", R.color.transparent),
    ExtendedFloatingActionButton("Extended Floating Action Button", R.color.transparent),
    FloatingActionButton("Floating Action Button", R.color.transparent),
    GridLayout("Grid Layout", R.color.transparent),
    GridView("Grid View", R.color.transparent),
    ImageButton("Image Button", R.color.transparent),
    ImageSwitcher("Image Switcher", R.color.transparent),
    ImageView("Image View", R.color.transparent),
    Magnifier("Magnifier", R.color.transparent),
    MaterialButton("Material Button", R.color.transparent),
    MaterialButtonToggleGroup("Material Button Toggle Group", R.color.transparent),
    MaterialCardView("Material Card View", R.color.transparent),
    MaterialTextView("Material Text View", R.color.transparent),
    MediaController("Media Controller", R.color.transparent),
    Menu("Menu", R.color.transparent),
    MultiAutoCompleteTextView("Multi Auto Complete Text View", R.color.transparent),
    NumberPicker("Number Picker", R.color.transparent),
    ProgressBar("Progress Bar", R.drawable.progress_bar),
    RadioButton("Radio Button", R.drawable.radio_buttons),
    RatingBar("Rating Bar", R.color.transparent),
    RecyclerView("Recycler View", R.color.transparent),
    SeekBar("Seek Bar", R.drawable.seek_bar),
    SnackBar("Snack Bar", R.color.transparent),
    Spinner("Spinner", R.color.transparent),
    StatusBar("Status Bar", R.drawable.status_bar),
    Switch("Switch", R.color.transparent),
    TabLayout("Tab Layout", R.color.transparent),
    TextClock("Text Clock", R.drawable.text_clock),
    TextView("Text View", R.color.transparent),
    TimePicker("Time Picker", R.drawable.time_picker),
    Toast("Toast", R.drawable.toast),
    ToolBar("Tool Bar", R.drawable.tool_bar),
}